### ISSUE TITLE
Force cohorts to update without logging in users

### ISSUE THREAD

**Issue by lukecarr** [catalyst/moodle-local_cohortauto#13]
From what I can understand, this plugin updates cohorts when a user logs in (for that user). Is there any way that we can run a one-off task that performs a bulk sync of all users? We have set-up 13 templates that we'd like to use to sync cohorts, and we have a couple thousand users, but we'd like users to show up in a course gradebook even if they haven't logged in (right now they won't show up until they login because they aren't yet in the cohort). Any ideas?

**Comment by lukecarr** [comment]
Nevermind, it turns out I can't read the README!

For future browsers who were as unobservant as me, you need to invoke the `local/cohortauto/cli/sync_users.php` CLI script!

**Comment by danmarsden** [comment]
haha - great to hear the readme had it - I couldn't remember if we'd added it in or not either! :-)
