### ISSUE TITLE
Can't delete generated cohorts

### ISSUE THREAD

**Issue by aquaino** [catalyst/moodle-local_cohortauto#14]
Hi,
first of all thank you for the development of this useful plugin.

I'm not able to modify (add or remove users) or delete an auto-generated cohort. Is there a way to achieve this? Is this normal?

Thank you 

![immagine](https://user-images.githubusercontent.com/58973551/112130952-4bb87800-8bc9-11eb-9cb3-d0e62d37d879.png)

**Comment by danmarsden** [comment]
Good to hear you find it useful - yes this is normal - any changes you made (add/removal of users) would be overridden by the plugin - the plugin does have a conversion tool that allows you to convert a cohort to be a manual cohort (breaking the link with the auto-cohort) which would allow you to modify/delete it as required.
