### ISSUE TITLE
Compatible moodle 4.X ?

### ISSUE THREAD

**Issue by kcalvat** [catalyst/moodle-local_cohortauto#19]
Hello teams,

Do you think this plugin will be compatible with moodle 4.X ? Will you make update for the next release ?

Thank you in advance,
Best regards :)

**Comment by danmarsden** [comment]
@kcalvat we don't have anyone using this plugin with an early plan for a 4.0 upgrade  we will probably test it on 4.0 at some point, but can't give a time frame - best way to know would be to test it yourself and report any issues to the tracker - thanks.
