### ISSUE TITLE
Problems when using the Plugin

### ISSUE THREAD

**Issue by Unbuckle** [catalyst/moodle-local_cohortauto#27]
Do not know where to post this elsewhere but I need some support with the plugin.

I have tried using this with OpenID Connect but it does not seem to work. Does the plugin listen to every login as well or only if a profile gets created/updated?

We have the following superstructure in the company and want to put users into cohorts based on the domain:

- internal users have name@companyname.com
- external users have name@external.companyname.com
- and partner users have name@partner.companyname.com

So in my case, if I understand how the plugin works correctly I would write I would write
{{ email.domain) }} in the (`mainrule_fld`) right
and then in (`replace_arr`)
I would say okay:
companyname.com|Internal
external.companyname.com|Partner
partner.companyname.com|External

Would that make sense?

However, I cannot even find where to modify the plugin after the initial installation. Have not worked with Moodle as much yet so sorry for the inconvenience.

**Comment by danmarsden** [comment]
best place to ask for free help/support using our plugins is in the moodle.org forums - we typically use the issues tracker in our github repositories only for tracking technical bugs and feature requests - I've responded to your post in the forums - thanks! :-)
