### ISSUE TITLE
Moodle 4.0 or 4.1

### ISSUE THREAD

**Issue by crnfpp** [catalyst/moodle-local_cohortauto#28]
Hi!
Is there a roadmap for 4.x compatibility or it's still not on the menu?
In case you need dev help or help testing functionality let me know!
Filippo

**Comment by danmarsden** [comment]
we have this running on a 3.9 site at the moment and the client is looking to upgrade to 4.1 in the next 6 months so we might take a look at it sometime - of course pull requests are always welcome.
