### ISSUE TITLE
cli/sync_users.php: show username being processed only if necessary

### ISSUE THREAD

**Issue by jpahullo** [catalyst/moodle-local_cohortauto#36]
Hi,

We use this plugin in our production site, with almost 79000 users, and it produces a very long output (file, email, whatever).

The version we used before, this output was not produced. Really, I like the idea of showing debugging information with the username being processed. However, for a normal execution, it is an unnecessary output, in my opinion.

I propose you to have a plugin setting, like "Enable sync debug", a checkbox, so that if enabled, this usernames listing is shown, and if disabled, it is not shown.

I mean:

1. Enable sync debug: Yes
```
Beginning user cohort sync...
- User 'username1' ...done.
- User 'username2' ...done.
[...]
- User 'username78693' ...done.
Sync for 78693 users finished.
```
2. Enable sync debug: No
```
Beginning user cohort sync...
Sync for 78693 users finished.
```

This way, with "Enable sync debug: No", it is really clear that it was processed and all was ok. Otherwise, some output will be shown with the exception being thrown.

If we need at some time know really which users were processed, we can then "Enable sync debug: Yes" and then follow the output and verify if the username appears on the list.

Related to this, it can also be interesting to have some field informing the last time the user's cohorts were synced. It could be a user preference, for instance, of configurable on the plugin settings allowing to define a user field (user field or custom profile field), so if it is defined, it is set just after processing the user, or just triggering an event informing that the user was processed by the plugin.

If you are interested in the first part or also the second part, we could provide a patch.

Thanks,

Jordi

**Comment by danmarsden** [comment]
yeah - sounds great - FYI - my time spent on "community" contributions has been focused on clearing the moodle.org plugins db review queue recently - hopefully I'll that will get cleared off soon and I'll get a chance to come back to some of the pull requests in various other plugins like this one sometime.... but if it's a simple PR I'll try to get to it quick!

**Comment by danmarsden** [comment]
finally got round to merging these - thanks!
