### ISSUE TITLE
Is there a way to use email.rootdomain to combine cohorts?

### ISSUE THREAD

**Issue by nkr1ptd** [catalyst/moodle-local_cohortauto#5]
For example lets say I have 3 cohorts employee, partners and customers.
I want all abcCompany.com people to go into the employee cohort.
I can specify the different partner domains to direct all to the partners cohort 
But then I want all others not listed above to go into a customer cohort.

Is this possible?

**Comment by danmarsden** [comment]
When you have a small number of cohorts, or if you already know the names of the cohorts you want to use, then the following cohort plugin is probably better for your use case:
https://moodle.org/plugins/local_profilecohort

The cohortauto plugin is more useful when you have heaps of different cohorts and need to have them created at the same time.

**Comment by nkr1ptd** [comment]
the local_profilecohort only pulls from custom fields not from email.  It does allow for what I am asking.  I only listed 3 cohorts but we will have many more, short of adding a field for these things, which means I have to trust them then this plugin is the best option to be honest.  Just wish it had the ability to do a rename on one the created cohort for all things not listed above in the renaming area.  Basically a wildcard if that makes sense.

**Comment by danmarsden** [comment]
feel free to help by submitting a pull request, or contracting your local moodle partner to make changes and pass through a pull request! :-)
