### ISSUE TITLE
Moodle 3.9 issues

### ISSUE THREAD

**Issue by johnpap21** [catalyst/moodle-local_cohortauto#9]
Hello

We have  migrated from 3.7 to 3.9 and the plugin has failed to generate any of the cohorts as it did before.

We don't get anything created.  
Use old AUTH_MCAE - User logs in - creates the cohort
Convert is using the tool to Auto-Cohort, 
Log out learner and log in again, user remains in cohort, doesnt create a new version of the AUTH_MCAE cohort

Kindest Regards
John

**Comment by danmarsden** [comment]
HI John - there isn't enough information here for us to investigate - have you configured the new local_cohort auto plugin? - it doesn't migrate any settings from the old auth_mcae plugin.

**Comment by johnpap21** [comment]
> HI John - there isn't enough information here for us to investigate - have you configured the new local_cohort auto plugin? - it doesn't migrate any settings from the old auth_mcae plugin.

Yes, it had all been set up and worked fine, so copied over the same settings to our pre-prod server which we had upgraded to 3.9

**Comment by danmarsden** [comment]
you probably need to set developer debug and display errors = on, then trace code to see if the local_cohortauto_handler function is being triggered correctly on user update. - can't help much  further at this stage sorry!

**Comment by johnpap21** [comment]
Thanks for that bit of help anyway, will do this.
